#!/bin/sh
. "$(dirname "$0")/_/husky.sh"

# a guard against non-interactive shells
[ -z "$NVM_DIR" ] && export NVM_DIR="$HOME/.nvm"
[ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"

nvm use

npx lint-staged --relative
